GET http://localhost:3333/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmNjMyNmY3Ny02NjYyLTQ3YzgtYjk0OS03NjgzZDZkMzNiNzYiLCJpYXQiOjE3MzAyMjU1MDgsImV4cCI6MTczMDIyOTEwOH0.qDj5M4JM0xdNTrPtgRooMA84HBK1qqRCC64SJYS25AM