GET http://localhost:3333/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjOTMzZmQ5Yi02OGMyLTQ5ODYtODIxOC1jNjc1Zjc1ZWM0N2QiLCJpYXQiOjE3MzAyMDkxMDgsImV4cCI6MTczMDIxMjcwOH0.Y558TmJWcWPgkpZYJ5N1WSYTbVKCPKcwUb7fKSGrL8Q